//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _25_EntityUsing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NORTHWNDEntities : DbContext
    {
        public NORTHWNDEntities()
            : base("name=NORTHWNDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<dataGetir_Result> dataGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dataGetir_Result>("dataGetir");
        }
    
        public virtual ObjectResult<getirData_Result> getirData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getirData_Result>("getirData");
        }
    
        public virtual int prcAra(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prcAra", araParameter);
        }
    
        public virtual ObjectResult<ara_Result> ara(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ara_Result>("ara", araParameter);
        }
    }
}
